server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /calcular {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
    }

    location /tasas {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
    }
}
